r_bn:  10.0
lr:  0.25
Computing sample features for class 0
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 1
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 2
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 3
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 4
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 5
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 6
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 7
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 8
centroid_image shape: torch.Size([10, 3, 224, 224])
Computing sample features for class 9
centroid_image shape: torch.Size([10, 3, 224, 224])
Traceback (most recent call last):
  File "data_synthesis_new.py", line 414, in <module>
    bc, sample_weights, ct_images = get_bary(args)
  File "data_synthesis_new.py", line 281, in get_bary
    print(f'Total centroid_images shape: {centroid_images.shape}')
AttributeError: 'list' object has no attribute 'shape'
=> using pytorch pre-trained model 'resnet18'
process data from ../recover/syn_data/imagenette/447
Traceback (most recent call last):
  File "generate_soft_label.py", line 253, in <module>
    main()
  File "generate_soft_label.py", line 126, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "generate_soft_label.py", line 198, in main_worker
    bary_weights_map = load_weights_file(args.data, os.path.join(args.data, 'sample_weights.txt'))
  File "/media/techt/One Touch/DD/SRe2L/relabel/utils_fkd.py", line 314, in load_weights_file
    with open(weight_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../recover/syn_data/imagenette/447/sample_weights.txt'
W&B disabled.
W&B online. Running your script from this directory will now sync to the cloud.
wandb: Currently logged in as: hl57. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.10
wandb: Run data is saved locally in /media/techt/One Touch/DD/SRe2L/train/wandb/run-20231030_145254-k043q2w5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run macabre-phantasm-576
wandb: ‚≠êÔ∏è View project at https://wandb.ai/hl57/final_rn18_fkd
wandb: üöÄ View run at https://wandb.ai/hl57/final_rn18_fkd/runs/k043q2w5
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run macabre-phantasm-576 at: https://wandb.ai/hl57/final_rn18_fkd/runs/k043q2w5
wandb: Ô∏è‚ö° View job at https://wandb.ai/hl57/final_rn18_fkd/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjk3MzkyNjU3/version_details/v51
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231030_145254-k043q2w5/logs
Traceback (most recent call last):
  File "train_FKD.py", line 399, in <module>
    main()
  File "train_FKD.py", line 110, in main
    bary_weights_map = load_weights_file(args.train_dir, os.path.join(args.train_dir, 'sample_weights.txt'))
  File "/media/techt/One Touch/DD/SRe2L/train/../relabel/utils_fkd.py", line 314, in load_weights_file
    with open(weight_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../recover/syn_data/imagenette/447/sample_weights.txt'
