nohup: ignoring input
=> using pytorch pre-trained model 'resnet18'
process data from ../recover/syn_data/tiny-imagenet/t1
  0%|          | 0/10 [00:00<?, ?it/s] 10%|█         | 1/10 [00:06<00:54,  6.08s/it] 20%|██        | 2/10 [00:08<00:30,  3.79s/it] 30%|███       | 3/10 [00:10<00:21,  3.10s/it] 40%|████      | 4/10 [00:13<00:17,  2.86s/it] 50%|█████     | 5/10 [00:15<00:14,  2.85s/it] 60%|██████    | 6/10 [00:18<00:11,  2.78s/it] 70%|███████   | 7/10 [00:21<00:08,  2.86s/it] 80%|████████  | 8/10 [00:23<00:05,  2.71s/it] 90%|█████████ | 9/10 [00:26<00:02,  2.74s/it]100%|██████████| 10/10 [00:29<00:00,  2.63s/it]100%|██████████| 10/10 [00:29<00:00,  2.91s/it]
======= FKD: dataset info ======
path: ../relabel/FKD_cutmix_fp16/tiny-imagenet/t1/
num img: 200
batch size: 50
max epoch: 10
================================
load data successfully
=> loading student model 'resnet18'
TRAIN Iter 0: lr = 0.001000,	loss = 0.036159,	Top-1 acc = 0.500000,	Top-5 acc = 3.500000,	train_time = 41.669935
TEST Iter 0: loss = 15.559106,	Top-1 acc = 0.530000,	Top-5 acc = 2.380000,	val_time = 63.135732
TEST Iter 9: loss = 10.325552,	Top-1 acc = 0.640000,	Top-5 acc = 2.470000,	val_time = 60.340046
Traceback (most recent call last):
  File "data_synthesis.py", line 357, in <module>
    save_arguments(script_name, args)
  File "/media/techt/One Touch/DD/SRe2L/recover/utils.py", line 35, in save_arguments
    if entry["script"] == script_name:
KeyError: 'script'
=> using pytorch pre-trained model 'resnet18'
process data from ../recover/syn_data/imagenette/t1
Traceback (most recent call last):
  File "generate_soft_label.py", line 255, in <module>
    main()
  File "generate_soft_label.py", line 126, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "generate_soft_label.py", line 201, in main_worker
    train_dataset = ImageFolder_FKD_MIX(
  File "/media/techt/One Touch/DD/SRe2L/relabel/utils_fkd.py", line 155, in __init__
    super(ImageFolder_FKD_MIX, self).__init__(**kwargs)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: '../recover/syn_data/imagenette/t1'
Traceback (most recent call last):
  File "train_FKD.py", line 379, in <module>
    main()
  File "train_FKD.py", line 95, in main
    assert os.path.exists(args.train_dir)
AssertionError
